#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

whyteboard = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAByZJ"
    "REFUWIXFl8tvG8cdgL9d7otLUpQtirJkSjIjpVBSFy3qh4Q8AAeNU7hAivZaJH9FLwUaFOjr"
    "XKD39FKg1x5zKQy0cZFEthy/9LBFMjIpUi+S4mPJfczuTg9ylCa1kwCx0wEGs5eZ79vf7zc7"
    "s4qiJvh/Nu3bAjluIB0/QkOSMhUMXSOh6cq3IhCFQv75Xzv87UYHDju8/b2Yt358FvgWIhCF"
    "Qv7pH2Wu76n8/OU53n2vxDt/vY3u7j57Ac8dSgZN6k3Bfj/Fu++VKN3ZI9GOuH37Dk6/JxOK"
    "oj4z+O7uLlbSZvJkhr//s8zd6wck2rv8aGaT01mXfD73bCLguUNZr9dJp9PY2ZwybD2Uv7zo"
    "85fmPl7rEwqpHWZnz5IZyT59Ac8dylqtRjqdZuLUpPJw6xP54a1NEv4uP32+TD2zz96hZCw3"
    "TjqVeroCvufKWq2GYRhMTp1WatWqLJdLbG/XKZVKtFptHMcjn88zNTlJNpvlqRWA8D1ZrVaJ"
    "oojZM0Wlvl2TlUqZWq1GuVyi0znEdV2y2SyLi4ucPXuWTCbzdARCEcjdvX38IOC5YpGdRl2W"
    "yxWqtRqVSoXDw0Mcx8G2bV566SVeeeUVcrkcCU1/OlsgiiLazT2mp6bo9npsbpao1apUymVa"
    "rRaO42CaJotLS1y6dIlTk1NKQtMV4JtHQAS+rG6VsLIT2KkU1WqVRqNOpVLh4OCAfr+Pqqqc"
    "P3+e1y69xqnJKeW/538jgSgUsrS5QS+0OFOYoFqrUd/ePoYPh0MAFpcWuXz5MoXpaeWLa2gA"
    "A6cvV1Zu0mjUAYjjmCiOjwwVhTiOUVWVWEoUFCQSpKRS2qAf6nx/YYb93R0qlQr3HzygXq/j"
    "+z5RFLG0tMQbl99gZvbM/8CPBZrNJo1Gnddff51ut0sikUBRFMIwJBQCEYZEwicIY6IoxPN8"
    "NBmy2ejw8g9epN1qslkqsbp6j62tLXzfx/d9Ll68yJUrV5g9U3ws/FhASolhGOTG88r+3p7c"
    "2Njg7t07GKaBjCUAUlFRZIwvJPNzswjXZ/qFBQzLYm1tlXt373L//gMcxwHg3LlzXLlyhTPF"
    "554IPxZQFAUhBJ3DtozjmL7j8N2z57hw4SKDoYsXuIggQDctdEOj3djCzpwkZZusr6/z8a2P"
    "Wd/YwLZtZmZmCIKAV199lfnnv/OlcHhUhMmkDUC5XEbTNLIZC8tK4AYeIg4IfB9FVTEMg/LG"
    "OlJR6XZbrKzc4Nr773NvdR3TMHjzzTeZnZ2l1+vR7/e/iv2ZQCplk7RTNOp14jimMD1DGMbs"
    "7OwTxxKJRE0kUFQVXYsplTbZfPCA1dVV1tdWGT0xxq9+80fK5TKj2RHy+Tw3btzg/vqa/HoC"
    "6Yzy4gsLDF2XVquFadrs7tRo7e8i45hEQkM3DBIKtJstkDH37h0V3MmxHO/87rcIEVCcX8D3"
    "XE6fLrCzs0Nla+vrRQDAtm3CMGR7e5soipmaHEc3wPU8NE0j8ejyura+xp176wwHfQrFeX79"
    "+z/Q7TjIOGZsbIxuf0Amk2Z6usCHH3zAyo3rXxqF49Mwm82SStm0Wi2KxSL5iUnuPyhjJjOM"
    "ZEbQLZ1mo8Fus8cLP1zkZz+5TNI26B4OCUWICAJGs2Ocv7DErZvLjOXG2dvbZ3l5mUZ9W06d"
    "Ljz5O/BpGj6+uSJv375Nr9/H1HX6vS6ZURdFVZESHG/IW2//gpGRLO7QRYgYGT/qUmJYJml5"
    "EsOw0XSViYk8lUqFavXhV6cAIJPJEEURzYMDgjCkMDWJEIIgDFFRODUxhRCSXreP4wyI44hY"
    "RvT6Q3wR4rseqpogf6pAr9djLDeOZVlcu/Zv7m+sPzYVn7uQpNNpYhnTbDYZz+fJZNKEvQHt"
    "Vgt34GBYBr1uB9/zSaUsum0LVVXpdPqEYYimaQghaDab2LZFKp1lPJfjYbXKrVu36By25eiJ"
    "k8oTBXK5HIXTBRqNBsPBgDiW6FqCzkGdQwkJVcHpdWm3mqTs5NGVytBRVRVv0EOIEC8QhMKn"
    "0x7SLx0dSlEUsbW1RbVaJRSB1HRDeayAphvK+tqqrFQqdDodxsbGkDJC5Sh6URRxYnQEXdeI"
    "Y0kgAg67PRzHYTgc4rru8eh5Hp7nHa99cHBAvV5nbm7uySkAGB0dRVVVNjY2mJ+fxzAMAiEI"
    "fB/XdRkMBgRBcDwKIQiC4Og5CPCDAM/zjlOSTCYxTZNCocD83ByWZX2Opzzu5/T68kfy6tWr"
    "DIdDTNMkiiLiOD5+K9/38TwPIQSapmEYBrZtY1nWcTdNE9M0SWcynBgdZWFhgdnZWXTDVL5S"
    "IBSBXFm5yfLyR+zv7+O6LoqioGkaum5gWSaGYXwGSaePoalUCssyyeXGyefzKIqC+ugc+SL8"
    "sSn4tBYa9W0ZhoJev48QIaoCuq6j6zqmeSSQTCYpFoufm6uqRztb07THAr/Y/gMUGsdwDkYU"
    "8wAAAABJRU5ErkJggg==")
getwhyteboard2Data = whyteboard.GetData
getwhyteboard2Image = whyteboard.GetImage
getwhyteboard2Bitmap = whyteboard.GetBitmap
getwhyteboard2Icon = whyteboard.GetIcon